@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0MywibmFtZSI6IklsZSIsInVzZXJuYW1lIjoiaWxlIiwiZW1haWwiOiJpbGVAbWV0cm9wb2xpYS5maSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzc1MDQ1Mzg5LCJleHAiOjE3NzUxMzE3ODl9.52Wi7LypfTsYYg11cdH95hCf7NKtBLkiftOy9uUFVUw

GET http://127.0.0.1:3000/api/v1/cats


### lisätään kissa
POST http://127.0.0.1:3000/api/v1/cats
Content-Type: multipart/form-data; boundary=MyBoundary
Authorization: Bearer {{token}}

--MyBoundary
Content-Disposition: form-data; name="cat_name"

Misu
--MyBoundary
Content-Disposition: form-data; name="weight"

6
--MyBoundary
Content-Disposition: form-data; name="birthdate"

2023-10-08
--MyBoundary
Content-Disposition: form-data; name="cat"; filename="dog.jpg"
Content-Type: image/jpeg

< ./dog.jpg
--MyBoundary--

### hae kissa id:n perusteella
GET http://127.0.0.1:3000/api/v1/cats/9592


### päivitä kissan tietoja
PUT http://127.0.0.1:3000/api/v1/cats/9592
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "cat_name": "Don Corleone"
}

### poistetaan kissa
DELETE http://127.0.0.1:3000/api/v1/cats/9592
Authorization: Bearer {{token}}
