GET http://127.0.0.1:3000/api/v1/cats


### lisätään kissa
POST http://127.0.0.1:3000/api/v1/cats
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="cat_name"

Misu
--MyBoundary
Content-Disposition: form-data; name="weight"

6
--MyBoundary
Content-Disposition: form-data; name="owner"

37
--MyBoundary
Content-Disposition: form-data; name="birthdate"

2023-10-08
--MyBoundary
Content-Disposition: form-data; name="cat"; filename="dog.jpg"
Content-Type: image/jpeg

< ./dog.jpg
--MyBoundary--

### hae kissa id:n perusteella
GET http://127.0.0.1:3000/api/v1/cats/9592


### päivitä kissan tietoja
PUT http://127.0.0.1:3000/api/v1/cats/9592
Content-Type: application/json

{
  "cat_name": "Don Corleone"
}

### poistetaan kissa
DELETE http://127.0.0.1:3000/api/v1/cats/9592
