GET http://127.0.0.1:3000/api/v1/users


### lisätään user
POST http://127.0.0.1:3000/api/v1/users
Content-Type: application/json

{
  "username": "Vito",
  "name": "Juha",
  "email": "juha.tauriainen@metropolia.fi",
  "role": "teacher / failed comedian",
  "password":"tähän oman pankin salasana"
}

### hae user id:n perusteella
GET http://127.0.0.1:3000/api/v1/users/9592


### päivitä userin tietoja
PUT http://127.0.0.1:3000/api/v1/users/9592
Content-Type: application/json

{
  "username": "Don Corleone"
}

### poistetaan user
DELETE http://127.0.0.1:3000/api/v1/users/9592
